[tool.poetry]
name = "otterdog"
version = "0.1.0.dev"
description = "Tool to manage GitHub organizations and their repositories."
authors = ["Thomas Neidhart <thomass.neidhart@eclipse-foundation.org>"]
readme = "README.md"
packages = [{include = "otterdog"}]

[tool.poetry.dependencies]
python = "^3.10"
playwright = "~1.31.0"
jq = "~1.4.1"
colorama = "~0.4.6"
mintotp = "~0.3.0"
requests = "~2.28.2"
jsonschema = "~4.17.3"
JSONBender = "~0.9.3"
importlib_resources = "~5.12.0"
requests-cache = "~1.0.1"
gojsonnet = "~0.20.0"

[tool.poetry.group.test]

[tool.poetry.group.test.dependencies]
pytest = "~7.3.1"

[tool.poetry.scripts]
otterdog = "otterdog.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "7.2"
testpaths = ["tests"]
pythonpath = [".", "otterdog"]