version: '3.8'

services:
  webapp:
    restart: always
    env_file: ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./start-webapp
    ports:
      - 5000:5000
    volumes:
      - ../github-app:/app/work/config

#  nginx:
#    container_name: nginx
#    restart: always
#    image: "nginx:latest"
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - webapp
