name: Ingest SBOM into Sonatype Lifecycle

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.12'
      - name: Install cyclonedx-py
        run: pipx install cyclonedx-bom
      - name: Generate sbom
        run: cyclone-dx poetry --no-dev -o otterdog-bom.json
      - name: Nexus IQ Policy Evaluation
        uses: sonatype-nexus-community/iq-github-action@master
        with:
          serverUrl: https://sonatype-lifecycle.eclipse.org
          username: bMingMXb
          password: ${{ secrets.IQ_TOKEN }}
          applicationId: otterdog-main
          stage: Build
          target: otterdog-bom.json
      - name: Upload sbom
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          path: otterdog-bom.json
